stages:
  - build
  - test
  - build_docker_image
  - deploy

build:
  stage: build
  image: golang:1.22.1
  script:
    - go mod download
    - go mod verify
    - go build -v -o cicd-service-go ./cmd/app

test:
  stage: test
  image: golang:1.22.1
  script:
    - go test -v ./...

build_docker_image:
  stage: build_docker_image
  image: docker:latest
  script:
    - docker build -t registry.local:5000/cicd-service-go:cicd-test .
    - docker push registry.local:5000/cicd-service-go:cicd-test

deploy:
  stage: deploy
  image: registry.local:5000/cicd-ansible:latest
  script:
    - cd ./ansible/
    - ansible-playbook --inventory inventories/hosts-service.ini playbooks/deploy.yml
