stages:
  - build
  - test
  - build_docker_image
  - deploy
  - destroy

build:
  stage: build
  image: golang:1.22.1
  script:
    - go mod download
    - go mod verify
    - go build -v -o cicd-service-go ./cmd/app

test:
  stage: test
  image: golang:1.22.1
  script:
    - go test -v ./...

build_docker_image:
  stage: build_docker_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"insecure-registries\":[\"http://registry.local:5000\"]}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor 
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination registry.local:5000/cicd-service-go:gitlab-test
      --insecure
      --cache=true

deploy:
  stage: deploy
  image: registry.local:5000/cicd-ansible:latest
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - cd ./ansible/
    - ansible-playbook --inventory inventories/hosts-gitlab.ini playbooks/deploy.yml

destroy:
  stage: destroy
  image: registry.local:5000/cicd-ansible:latest
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - cd ./ansible/
    - ansible-playbook --inventory inventories/hosts-gitlab.ini playbooks/destroy.yml
