pipeline:
  steps:
    - name: Build
      image: golang:1.22.1
      branch: test03
      commands:
        - go mod download
        - go mod verify
        - go build -v -o cicd-service-go ./cmd/app

    - name: Test
      image: golang:1.22.1
      branch: test03
      commands:
        - go test -v ./...

    - name: Build and Push docker image
      image: docker:26.1.1-dind-alpine3.19
      branch: test03
      commands:
        - docker build -t registry.local:5000/cicd-service-go:cicd-test-02 .
        - docker push registry.local:5000/cicd-service-go:cicd-test-02

    - name: Deploy to DEV
      image: registry.local:5000/cicd-ansible:latest
      branch: test03
      commands:
        - export ANSIBLE_HOST_KEY_CHECKING=False
        - cd ./ansible/
        - ansible-playbook --inventory inventories/hosts-service.ini playbooks/deploy.yml

    - name: Destroy on DEV
      image: registry.local:5000/cicd-ansible:latest
      branch: test03
      commands:
        - export ANSIBLE_HOST_KEY_CHECKING=False
        - cd ./ansible/
        - ansible-playbook --inventory inventories/hosts-service.ini playbooks/destroy.yml
