pipeline:
  steps:
    - name: Build
      image: golang:1.22.1
      commands:
        - echo "Build cicd-service-go"
        - go mod download
        - go mod verify
        - go build -o cicd-service-go ./cmd/app
        - echo "Build cicd-service-go DONE"

    - name: Test
      image: golang:1.22.1
      commands:
        - echo "Tests for cicd-service-go"
        - go test ./...
        - echo "Tests for cicd-service-go DONE"

    - name: Build Docker Image
      image: docker:latest
      commands:
        - echo "Build docker image cicd-service-go:latest"
        - docker build -t cicd-service-go:latest .
        - docker tag cicd-service-go:latest registry:5000/cicd-service-go:latest
        - docker push registry:5000/cicd-service-go:latest
        - echo "Build docker image cicd-service-go:latest DONE"

    - name: Push Docker Image
      image: docker:latest
      commands:
        - docker tag cicd-service-go:latest registry:5000/cicd-service-go:latest
        - docker push registry:5000/cicd-service-go:latest

    - name: Deploy
      image:
      commands:
        - ./deploy.sh
