version: '3.9'

networks:
  default:
    name: cicd-network
    ipam:
      driver: default
      config:
        - subnet: 172.102.0.0/16

volumes:
  etcd-data:
  vault-data:

services:
  cicd-service-01:
    image: cicd-service-go:test
    container_name: cicd-service-01
    build:
      dockerfile: ./Dockerfile.dind
    volumes:
      - ./configs/config-test.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - etcd

  cicd-service-02:
    image: cicd-service-go:test
    container_name: cicd-service-02
    build:
      dockerfile: ./Dockerfile.dind
    volumes:
      - ./configs/config-test.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3010:3000
    restart: always
    depends_on:
      - etcd

  cicd-service-03:
    image: cicd-service-go:test
    container_name: cicd-service-03
    build:
      dockerfile: ./Dockerfile.dind
    volumes:
      - ./configs/config-test.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3020:3000
    restart: always
    depends_on:
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    container_name: etcd
    command:
      - etcd
      - --name=etcd
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
    volumes:
      - etcd-data:/data.etcd
    ports:
      - 2379:2379
    restart: always

  vault:
    image: vault:1.13.3
    container_name: secrets
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_SERVICE_TOKEN: ${VAULT_SERVICE_TOKEN}
    ports:
      - "8200:8200"
    volumes:
      - secrets-data:/secrets/data
    cap_add:
      - IPC_LOCK
    restart: always
