@startuml
start
:Фиксация изменения в репозиторий VCS;
:Автоматический запуск webhook;

if (Используется Load Balancer?) then (да)
:Балансировка запроса webhook;
else (нет)
endif

if (Используется Virtual IP?) then (да)
:Назначить VIP-адрес на хост с мастер-узлом;
else (нет)
:Использовать статический IP адрес;
endif

if (Является ли узел получения запроса мастером?) then (да)
:Обработка полученного запроса на создание задания;
:Получение токена авторизации проекта из Vault для проверки прав на создание задания;

if (Токен авторизации для webhook верный?) then (да)
:Добавление задания в очередь DCS;
:Запуск планировщика заданий;
:Проверка статусов выполнения прошлых заданий;
:Отправка в архив выполненых (или с ошибкой) заданий;
:Запланировать новые задания на воркер-узлы;

if (Режим standalone?) then (да)
:Получить новые задания;
:Запуск выполения заданий через worker pool;
:Запись результатов в DCS;
else (нет)
endif

else (нет)
:Вывод ошибки авторизации;
endif

else (нет)
:Вывод информации о недопустимости выполнения команды на воркер-узле;
endif
end
@enduml
