@startuml

database "Version Control System" {
'    [GitHub, GitLab, Bitbucket] as VCS
}

database "Credential Store" {
'    [Vault]
}

database "Distributed Coordination Service" {
'    [Etcd1] .. [Etcd2]
'    [Etcd2] .. [Etcd3]
'    [Etcd3] .. [Etcd1]
}

package "cicd-service-go" {

    class Main

    class Manager

    class Scheduler

    class Worker
    class Taskpkg
    class Pipeline
    class Scripts
    class Sources
    class Etcd
    class Vault
    class Logs
    class Config

    Main --> Scheduler
    Main --> Manager
    Main --> Logs
    Main --> Vault
    Main --> Etcd

    Etcd --> Config
    Etcd --> Logs

    Vault --> Config
    Vault --> Logs

    Manager --> Etcd
    Manager --> Logs
    Manager --> Config

    Scheduler --> Worker
    Scheduler --> Taskpkg
    Scheduler --> Manager
    Scheduler --> Etcd
    Scheduler --> Logs

    Worker --> Sources
    Worker --> Taskpkg
    Worker --> Pipeline
    Worker --> Scripts
    Worker --> Etcd
    Worker --> Logs

'    Worker --> [Other Dependencies]

}




@enduml
