@startuml

top to bottom direction

database "Version Control System" {
    interface VCS_UI
    interface VCS_API
    VCS_API -- [GitHub, GitLab, Bitbucket]
    VCS_UI -- [GitHub, GitLab, Bitbucket]
}

database "Credential Store" {
    interface VAULT_API
    VAULT_API -- [Vault]
}

database "Distributed Coordination Service" {
    interface DCS_API
    DCS_API -- [Etcd1]
    DCS_API -- [Etcd2]
    DCS_API -- [Etcd3]

    [Etcd1] - [Etcd2]
    [Etcd2] -- [Etcd3]
    [Etcd3] -- [Etcd1]
}

package "Virtual IP" {
    interface VIP

    [Keepalived1] as KP1
    [Keepalived2] as KP2
    [Keepalived3] as KP3

    VIP <-r- KP1
    VIP <-r- KP2
    VIP <-r- KP3

    KP1 - KP2
    KP2 -- KP3
    KP1 -- KP3
}

package "Load Balancer" {
    [Nginx, HAProxy] as LB
}

package "CI/CD Service" {
    interface MASTER_API
    interface WORKER1_API
    interface WORKER2_API

    MASTER_API -d- [Master]
    WORKER1_API -d- [Worker1]
    WORKER2_API -d- [Worker2]
}

actor User

User ..> VCS_UI : Push commit in repository
User ..> VAULT_API : Add credentials in vault
User ..> LB : Use API cicd-service-go

note right of VAULT_API
Get or Add credentials
end note

[GitHub, GitLab, Bitbucket] ..> LB : Webhooks for commits or PR
LB ..> VIP : Direct traffic to VIP

note left of VIP
With the help of keepalived, the master is identified
and a vip address is assigned to its host.
end note

VIP ..> MASTER_API : Direct traffic to master CI/CD service

note right of MASTER_API
All work with the API goes through the master.
Other cluster members do not have such rights.
end note


KP1 -d..> MASTER_API : Find master
KP2 -d..> WORKER1_API : Find master
KP3 -d..> WORKER2_API : Find master

[Master] -u..> VAULT_API
[Worker1] -u...> VAULT_API
[Worker2] -u..> VAULT_API

'[Master] -up-> VCS_API
[Worker1] -u.> VCS_API
[Worker2] -u.> VCS_API

note left of VCS_API
Use for pull repository
end note

[Master] ..> DCS_API : Use storage
[Worker1] ..> DCS_API : Use storage
[Worker2] ..> DCS_API : Use storage

note right of DCS_API
Use for connection
Example connection string: Etcd1,Etcd2,Etcd3
end note

@enduml
